platforms:
- name: T2
  repo: https://github.com/tuya/TuyaOpen-T2
  branch: master
  commit: e34a96a0963fee6d6bf50f6fc184797014464719

- name: T3
  repo: https://github.com/tuya/TuyaOpen-T3
  branch: master
  commit: 065639a0a76c5f7c564509b8fd8b64f7949da4f5

- name: Ubuntu
  repo: https://github.com/tuya/TuyaOpen-ubuntu
  branch: platform_ubuntu
  commit: 3dee80f1cc2e18eaccf71125d8f86889a75aa907

- name: T5AI
  repo: https://github.com/tuya/TuyaOpen-T5AI
  branch: master
  commit: 3de816d169d7fbd1d94513dd945e2682bba329f3

- name: ESP32
  repo: https://github.com/tuya/TuyaOpen-esp32
  branch: master
  commit: 68fb67839199abc97d60f571c642cbf9e37b062d

- name: LN882H
  repo: https://github.com/tuya/TuyaOpen-ln882h
  branch: master
  commit: 3132855d1873ce065059e3647be58f6b608c3a1f

- name: BK7231X
  repo: https://github.com/tuya/TuyaOpen-bk7231x
  branch: master
  commit: 53b61a46c27406623cdf7e727a2958aca98a1cda

- name: L511C
  repo: https://github.com/freedom195/L511C
  branch: master
  commit: c8f61af3cbc2e59092eccc52c6c631c45789a48a